// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllCache() {
  return window['go']['service']['CacheStore']['DeleteAllCache']();
}

export function GetOrSetCache(arg1, arg2, arg3) {
  return window['go']['service']['CacheStore']['GetOrSetCache'](arg1, arg2, arg3);
}
