// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function DeleteAllCache():Promise<boolean>;

export function GetOrSetCache(arg1:service.CacheType,arg2:any,arg3:any):Promise<void>;
