// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function DefaultConfig():Promise<service.Config>;

export function DeleteConfigs(arg1:Array<any>):Promise<any>;

export function GetConfig():Promise<service.Config>;

export function RefreshConfig():Promise<any>;

export function SetConfigs(arg1:{[key: string]: string}):Promise<any>;
