// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultConfig() {
  return window['go']['service']['ConfigStore']['DefaultConfig']();
}

export function DeleteConfigs(arg1) {
  return window['go']['service']['ConfigStore']['DeleteConfigs'](arg1);
}

export function GetConfig() {
  return window['go']['service']['ConfigStore']['GetConfig']();
}

export function RefreshConfig() {
  return window['go']['service']['ConfigStore']['RefreshConfig']();
}

export function SetConfigs(arg1) {
  return window['go']['service']['ConfigStore']['SetConfigs'](arg1);
}
