// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApp() {
  return window['go']['service']['ConfigStore']['GetApp']();
}

export function GetIPTVView() {
  return window['go']['service']['ConfigStore']['GetIPTVView']();
}

export function Save() {
  return window['go']['service']['ConfigStore']['Save']();
}

export function SetApp(arg1) {
  return window['go']['service']['ConfigStore']['SetApp'](arg1);
}

export function SetIPTVView(arg1) {
  return window['go']['service']['ConfigStore']['SetIPTVView'](arg1);
}
