// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetApp():Promise<service.AppConfig>;

export function GetIPTVView():Promise<service.IPTVViewConfig>;

export function Save():Promise<void>;

export function SetApp(arg1:service.AppConfig):Promise<void>;

export function SetIPTVView(arg1:service.IPTVViewConfig):Promise<void>;
