// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetAllCategory():Promise<service.CategoriesResult>;

export function GetAllCountry():Promise<service.CountriesResult>;

export function GetAllLanguage():Promise<service.LanguagesResult>;

export function GetChannelWithStream(arg1:string):Promise<service.ChannelWithStreamsResult>;

export function GetFilteredChannels(arg1:service.IPTVFilter,arg2:string):Promise<service.ChannelsResult>;
