// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCategory() {
  return window['go']['service']['IPTV']['GetAllCategory']();
}

export function GetAllCountry() {
  return window['go']['service']['IPTV']['GetAllCountry']();
}

export function GetAllLanguage() {
  return window['go']['service']['IPTV']['GetAllLanguage']();
}

export function GetChannelWithStream(arg1) {
  return window['go']['service']['IPTV']['GetChannelWithStream'](arg1);
}

export function GetFilteredChannels(arg1, arg2) {
  return window['go']['service']['IPTV']['GetFilteredChannels'](arg1, arg2);
}
