// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CreatePlaylist(arg1:string):Promise<service.SinglePlaylistResult>;

export function CreatePlaylistItem(arg1:number,arg2:string):Promise<service.SinglePlaylistItemResult>;

export function DeletePlaylist(arg1:number):Promise<any>;

export function DeletePlaylistItem(arg1:number,arg2:string):Promise<any>;

export function GetAllCategory():Promise<service.CategoriesResult>;

export function GetAllChannelPlaylistItem(arg1:string):Promise<service.PlaylistItemsResult>;

export function GetAllCountry():Promise<service.CountriesResult>;

export function GetAllLanguage():Promise<service.LanguagesResult>;

export function GetAllPlaylist():Promise<service.PlaylistsResult>;

export function GetChannelWithStream(arg1:string):Promise<service.ChannelWithStreamsResult>;

export function GetFilteredChannels(arg1:service.IPTVFilter,arg2:string):Promise<service.ChannelsResult>;

export function UpdatePlaylist(arg1:number,arg2:string):Promise<service.SinglePlaylistResult>;
