// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlaylist(arg1) {
  return window['go']['service']['IPTV']['CreatePlaylist'](arg1);
}

export function CreatePlaylistItem(arg1, arg2) {
  return window['go']['service']['IPTV']['CreatePlaylistItem'](arg1, arg2);
}

export function DeletePlaylist(arg1) {
  return window['go']['service']['IPTV']['DeletePlaylist'](arg1);
}

export function DeletePlaylistItem(arg1, arg2) {
  return window['go']['service']['IPTV']['DeletePlaylistItem'](arg1, arg2);
}

export function GetAllCategory() {
  return window['go']['service']['IPTV']['GetAllCategory']();
}

export function GetAllChannelPlaylistItem(arg1) {
  return window['go']['service']['IPTV']['GetAllChannelPlaylistItem'](arg1);
}

export function GetAllCountry() {
  return window['go']['service']['IPTV']['GetAllCountry']();
}

export function GetAllLanguage() {
  return window['go']['service']['IPTV']['GetAllLanguage']();
}

export function GetAllPlaylist() {
  return window['go']['service']['IPTV']['GetAllPlaylist']();
}

export function GetChannelWithStream(arg1) {
  return window['go']['service']['IPTV']['GetChannelWithStream'](arg1);
}

export function GetFilteredChannels(arg1, arg2) {
  return window['go']['service']['IPTV']['GetFilteredChannels'](arg1, arg2);
}

export function UpdatePlaylist(arg1, arg2) {
  return window['go']['service']['IPTV']['UpdatePlaylist'](arg1, arg2);
}
