// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterFullScreen() {
  return window['go']['main']['App']['EnterFullScreen']();
}

export function ExitFullScreen() {
  return window['go']['main']['App']['ExitFullScreen']();
}

export function IsFullScreen() {
  return window['go']['main']['App']['IsFullScreen']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}
