// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterFullScreen():Promise<void>;

export function ExitFullScreen():Promise<void>;

export function IsFullScreen():Promise<boolean>;

export function Minimize():Promise<void>;

export function Quit():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function WindowShow():Promise<void>;
